### ISSUE TITLE
在ubuntu上构建失败

### ISSUE THREAD

**Issue by cake221** [zlgopen/awtk-quickjs#1]

**Comment by cake221** [comment]
src/c/tk_quickjs.c:81:10: fatal error: time_clock/digit_clock.h: No such file or directory
 #include "time_clock/digit_clock.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [src/c/tk_quickjs.o] Error 1
scons: building terminated because of errors.

这个是错误。谢谢

**Comment by cake221** [comment]
![捕获](https://user-images.githubusercontent.com/41943990/68731720-0581fa80-060c-11ea-90b8-1bcbb200a0a9.PNG)

请问一下，准备的第二项中，获取awtk-quickjs，是 https://github.com/zlgopen/awtk-js.git 地址么？

**Comment by cake221** [comment]
我刚才在 awtk-jerryscript 库中也做了尝试。还是同样的错误。

**Comment by xianjimli** [comment]
修改了。谢谢。更新一下AWTK和AWTK-quickjs

**Comment by cake221** [comment]
谢谢您这么快的回复。更新完代码后，ubuntu上已经成功运行起来了。

**Comment by cake221** [comment]
请问一下，现在awtk-quickjs是不是不能直接在windows上运行？这是我在windows系统上scons时的报错。
![捕获](https://user-images.githubusercontent.com/41943990/68743697-f8760300-062d-11ea-9594-7433669797ef.PNG)

**Comment by xianjimli** [comment]
是的。quickjs有些特性vs不支持。

**Comment by cake221** [comment]
嗯嗯。谢谢您的回答。
