### ISSUE TITLE
scons 出错

### ISSUE THREAD

**Issue by cake221** [zlgopen/awtk-quickjs#2]
拉了最近的一次代码。报了如下错误：

![捕获](https://user-images.githubusercontent.com/41943990/70373413-36abcd00-1923-11ea-8ee6-a43823f9d2ae.PNG)
![捕获2](https://user-images.githubusercontent.com/41943990/70373415-36abcd00-1923-11ea-9810-57c032b33eae.PNG)
![捕获3](https://user-images.githubusercontent.com/41943990/70373417-37446380-1923-11ea-9a8b-072aea447a54.PNG)
![捕获4](https://user-images.githubusercontent.com/41943990/70373418-37446380-1923-11ea-8626-fa9dbd30311b.PNG)
![捕获5](https://user-images.githubusercontent.com/41943990/70373420-37dcfa00-1923-11ea-867b-db6fa09a3201.PNG)

**Comment by xianjimli** [comment]
AWTK 本身要更新一些。

**Comment by cake221** [comment]
嗯嗯。谢谢您。
