### ISSUE TITLE
demos 的错误

### ISSUE THREAD

**Issue by cake221** [zlgopen/awtk-quickjs#3]
在 demos/basic.js 中，
![捕获](https://user-images.githubusercontent.com/41943990/70384783-b0919400-19bf-11ea-8a11-f5b88fa00152.PNG)

setShowFps 不在 TWidget，而在  TWindowManager 中。

**Comment by xianjimli** [comment]
好的，改了，你再试试。谢谢

**Comment by cake221** [comment]
好了。谢谢。
